;Filename: 	OPeNDAPExample_TimeSeries_SimpleExample.idl
;Author:	John Mejia (john.mejia@dri.edu), modified by Katherine Hegewisch(khegewisch@uidaho.edu)
;Updated: 	02/10/2015
;Description: 	This script uses OPeNDAP to download the specified subset of each of the 3 MACA products
; 		using the aggregated OPeNDAP URLs. In this program, 
;		output is saved into individual ASCII files for each GCM.
;Requirements: 	This IDL script is run using IDL version 8.4. OPeNDAP didn't work for IDL version 8.2.

;=============================================
;      SET TARGET DATA
;=============================================
;day =1;
lat_target=34.949852;
lon_target=-117.887785+360;
nameSta='Armstrong    ;identifier for final filename
;=============================================
;      SET OPENDAP PATHS FOR ALL 3 PRODUCTS(MACAV1METDATA,MACAV2LIVNEH,MACAV2METDATA)
;=============================================
datasetsMACA=['http://inside-dev1.nkn.uidaho.edu:8080/thredds/reacch_climate_CMIP5_aggregated_catalog.html',$
              'http://thredds.northwestknowledge.net:8080/thredds/nw.csc.macav2livneh.aggregated.html',$
              'http://inside-dev1.nkn.uidaho.edu:8080/thredds/reacch_climate_CMIP5_aggregated_macav2_catalog.html']

for idatast=0,n_elements(datasetsMACA)-1 do begin
    ;=====================
    ;loop over each MACA product
    ;=====================
    ourl = obj_new('IDLnetURL')
    content = ourl->get(url=datasetsMACA(idatast), /string_array)
    obj_destroy, ourl
    longnamearr=['']
    filenamearr=['']
    ;=====================
    ;find the filenames of all files from catalog for each MACA product
    ;=====================
    for istr=0,n_elements(content)-1 do begin
         a=str_sep(content(istr),'?dataset=')
         if n_elements(a) ge 2 then begin
             b=str_sep(a(1),"'><tt>")
             filename=b(0)
             longname=(str_sep(b(1),'</tt>'))(0)
             print, longname+': '+filename
             longnamearr=[longnamearr,longname]
             filenamearr=[filenamearr,filename]
        endif
    endfor
    ;=====================
    ;array of filenames
    ;=====================
    longnamearr=longnamearr(1:*)
    filenamearr=filenamearr(1:*)

    ;=====================
    ;loop over all files in the catalog for each MACA product
    ;=====================
    for ifile=0,n_elements(filenamearr)-1 do begin
      CATCH, Error_status
      IF Error_status NE 0 THEN BEGIN
        ifile=ifile+1
        CATCH, /CANCEL
      ENDIF
      
      urlnetcdf=(str_sep(datasetsMACA(idatast),'8080'))(0)+'8080'+'/thredds/dodsC/'+filenamearr(ifile)+'.nc
      cdfid = ncdf_open(urlnetcdf)
      
      ;=====================
      ;get metadata from file
      ;=====================
      inq= ncdf_inquire(cdfid)
      for i=0,inq.NGATTS-1  do begin
        attname = ncdf_attname(cdfid, i, /GLOBAL)
        ;print,attname
        ncdf_attget,cdfid,attname,attvalue, /GLOBAL
        ;print,attname,attvalue
        ;Save this attributes
      endfor
      var_ids = ncdf_varidsinq(cdfid)
      for ivars=0,n_elements(var_ids)-1 do begin
        test=ncdf_varinq(cdfid, var_ids[ivars])
        if test.NDIMS eq 3 then mainvar=test.NAME
      endfor
      
      names=strarr(inq.nvars)
      longname=strarr(inq.nvars)
      units=strarr(inq.nvars)
      calendar=strarr(inq.nvars)
      for i=0,inq.nvars-1 do begin
        info=ncdf_varinq(cdfid,i)
        names(i)=info.name
        print,names(i)
        FOR j=0,info.natts-1 DO BEGIN
          attname = ncdf_attname(cdfid,i,j)
          ncdf_attget,cdfid,i,attname,attvalue
          ;print, attname,':',string(attvalue)
          if attname eq 'units' then units(i)=string(attvalue)
          if attname eq 'calendar' then calendar(i)=string(attvalue)
          ;save all atributtes....
          ;do this
        ENDFOR
      endfor
      print, 'NAMES:'+names
      
      ;=====================
      ;extract time,lat,lon from file
      ;=====================
      ncdf_varget, cdfid, 'time', time
      ncdf_varget, cdfid, 'lon', xlon
      ncdf_varget, cdfid, 'lat', xlat
      
      ;=====================
      ;find index of closest grid point to this point
      ;=====================
      dist=abs(lat0-xlat)
      y0=where(dist eq min(dist))
      dist=abs(lon0-xlon)
      x0=where(dist eq min(dist))
      print,'.... extracting: '+mainvar+ '...'

      ;=====================
      ;extract data from file
      ;=====================
      ncdf_varget, cdfid, mainvar,var,COUNT=[1, 1, n_elements(time)], OFFSET=[x0, y0, 0]
      ncdf_close,cdfid
      
      ;=====================
      ;write ascii file
      ;=====================
      openw,1,filenamearr(ifile)+'.'+nameSta+'.txt'
      printf,1,longnamearr(ifile)
      printf,1,units
      printf,1,calendar
      for itime=0.0,n_elements(time)-1. do begin
        printf,1,time(itime),var(itime)
      endfor
      close,1
      ;=====================
    endfor ;each file
endfor ;each dataset
end
