;Filename: 	OPeNDAPExample_TimeSeries_SimpleExample.idl
;Author:	Katherine Hegewisch (khegewisch@uidaho.edu) from John Mejia's Advanced Example
;Updated: 	02/10/2015
;Description: 	This script uses OPeNDAP to download the specified subset of a MACAv2-METDATA file
;Requirements: 	This IDL script is run using IDL version 8.4. IDL version 8.2 didn't work with OPeNDAP.

;=============================================
;      SET TARGET DATA
;=============================================
;day =1;
lat_target=34.949852;
lon_target=-117.887785+360;
;=============================================
;      SET OPENDAP PATH, GET FILENAMES FROM CATALOG
;=============================================
urlnetcdf = 'http://inside-dev1.nkn.uidaho.edu:8080/thredds/dodsC/agg_macav1metdata_huss_BNU-ESM_r1i1p1_historical_1950_2005_WUSA.nc'; %this is for macav1-metdata only
cdfid = ncdf_open(urlnetcdf)

;Look at the contents of the file
inq= ncdf_inquire(cdfid)
;=============================================
;      GET LAT/LON/TIME
;=============================================
ncdf_varget, cdfid, 'lon', xlon
ncdf_varget, cdfid, 'lat', xlat
ncdf_varget, cdfid, 'time', time
;=============================================
;      FIND INDICES of CLOSEST GRID
;=============================================
;find indices of target lat/lon/day
dist=abs(lat0-xlat)
y0=where(dist eq min(dist))
dist=abs(lon0-xlon)
x0=where(dist eq min(dist))
;=============================================
;     GET DATA 
;=============================================
;data has 3 dimensions: lon,lat,time
ncdf_varget, cdfid, mainvar,var,COUNT=[1, 1, n_elements(time)], OFFSET=[x0, y0, 0]
;=============================================
;     CLOSE FILE
;=============================================
ncdf_close,cdfid  
;=============================================
